### ISSUE TITLE
What is the Node attribute `expanded` for ? 

### ISSUE THREAD

**Issue by UrbanSolution** [caesar0301/treelib#142] opened 2020-02-22 00:31 UTC
There is no documentation regarding the use of the Node class attribute `expanded`. What is it used for ?

**Comment by leonardbinet** [comment] 2020-02-22 05:43
Hello @UrbanSolution, this seems a duplicate of https://github.com/caesar0301/treelib/issues/132

**Closed** 2020-02-22 05:44 UTC
Labels: duplicate
